=== Manchick0/Wheel/schema/widget.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/Manchick0/Wheel/master/schema/widget.json",
  "title": "Widget",
  "description": "A Widget within the Wheel",
  "type": "object",
  "properties": {
    "label": {
      "type": ["string", "object", "array"],
      "description": "The label shown to the user when hovered."
    },
    "preview": {
      "oneOf": [
        {
          "type": "string"
        },
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "string",
              "description": "The identifier of the item."
            },
            "count": {
              "type": "integer",
              "description": "The count of the item stack."
            },
            "components": {
             "type": "object",
             "description": "The component map that is to be applied onto the item."
            }
          }
        }
      ],
      "type": ["string", "object"],
      "description": "An item that is to be shown on the widget."
    },
    "actions": {
      "type": "array",
      "items": {
        "$ref": "action.json",
        "description": "An action entry."
      },
      "description": "The actions performed by the widget."
    },
    "keep_opened": {
      "type": "boolean",
      "description": "Whether to keep the wheel opened after the Widget is pressed."
    },
    "take_slot": {
      "type": "string",
      "enum": [
        "top_left",
        "top",
        "top_right",
        "left",
        "right",
        "bottom_left",
        "bottom",
        "bottom_right"
      ],
      "description": "A pre-defined slot on the wheel that will be taken by this widget."
    }
  },
  "required": ["label", "preview", "actions"]
}

=== Manchick0/Wheel/src/main/resources/development/assets/development/widgets/root.json
{
  "label": [
    {
      "text": "\n "
    },
    {
      "translate": "widget.dev.root"
    },
    {
      "text": " \n\n "
    },
    {
      "translate": "widget.dev.root_description",
      "color": "gray"
    },
    {
      "text": " \n "
    },
    {
      "translate": "widget.dev.root_description_second",
      "color": "gray"
    },
    {
      "text": " \n"
    }
  ],
  "preview": "minecraft:structure_block",
  "take_slot": "bottom_right",
  "actions": [
    {
      "type": "open",
      "path": "dev"
    }
  ]
}

=== Manchick0/Wheel/src/main/resources/development/assets/development/widgets/dev/back.json
{
  "label": [
    {
      "text": "\n "
    },
    {
      "translate": "widget.wheel.back"
    },
    {
      "text": " \n\n "
    },
    {
      "translate": "widget.wheel.back_description",
      "color": "gray"
    },
    {
      "text": " \n "
    },
    {
      "translate": "widget.wheel.back_description_second",
      "color": "gray"
    },
    {
      "text": " \n"
    }
  ],
  "preview": "minecraft:command_block",
  "take_slot": "bottom",
  "actions": [
    {
      "type": "open",
      "path": ""
    }
  ]
}

=== Manchick0/Wheel/src/main/resources/building/assets/building/widgets/first_pos.json
{
  "label": [
    {
      "text": "\n "
    },
    {
      "translate": "widget.building.first_pos"
    },
    {
      "text": " \n\n "
    },
    {
      "translate": "widget.building.first_pos_description",
      "color": "gray"
    },
    {
      "text": " \n "
    },
    {
      "translate": "widget.building.first_pos_description_second",
      "color": "gray"
    },
    {
      "text": " \n"
    }
  ],
  "preview": "minecraft:wooden_axe",
  "take_slot": "bottom_left",
  "actions": [
    {
      "type": "command",
      "command": "//pos1"
    }
  ]
}

=== Manchick0/Wheel/src/main/resources/building/assets/building/widgets/second_pos.json
{
  "label": [
    {
      "text": "\n "
    },
    {
      "translate": "widget.building.second_pos"
    },
    {
      "text": " \n\n "
    },
    {
      "translate": "widget.building.second_pos_description",
      "color": "gray"
    },
    {
      "text": " \n "
    },
    {
      "translate": "widget.building.second_pos_description_second",
      "color": "gray"
    },
    {
      "text": " \n"
    }
  ],
  "preview": "minecraft:stone_axe",
  "take_slot": "bottom_right",
  "actions": [
    {
      "type": "command",
      "command": "//pos2"
    }
  ]
}
